#!/usr/bin/env python3
"""Create an ontology-first hardware IP scaffold."""

from __future__ import annotations

import argparse
import json
import re
import stat
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


SCHEMA_VERSION = "oag_ip_scaffold.v1"
DEFAULT_DIRS = [
    "req",
    "req/deep_semantic_intake",
    "ontology/evidence",
    "ontology/evidence/stage_runs",
    "ontology/drafts",
    "ontology/generated",
    "ontology/generated/authoring_packets",
    "ontology/gates",
    "ontology/metrics",
    "ontology/runs",
    "ontology/validations",
    "knowledge/records",
    "knowledge/views",
    "knowledge/views/_generated",
    "knowledge/views/promoted",
    "handoff/failure_tickets",
    "rtl",
    "tb/cocotb",
    "sim/waves",
    "lint/reports",
    "cdc",
    "cov/reports",
    "formal",
    "syn/reports",
    "syn/netlist",
    "sdc",
    "list",
    "doc",
    "scripts",
    "signoff",
]


def now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def slug(value: str) -> str:
    text = re.sub(r"[^a-zA-Z0-9_]+", "_", value.strip()).strip("_").lower()
    text = re.sub(r"_+", "_", text)
    if not text:
        raise ValueError("IP name cannot be empty")
    if not re.match(r"^[a-zA-Z_][a-zA-Z0-9_]*$", text):
        raise ValueError(f"invalid IP name after normalization: {text}")
    return text


def write(path: Path, content: str, *, force: bool, executable: bool = False) -> bool:
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    if executable:
        mode = path.stat().st_mode
        path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return True


def touch(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        path.write_text("", encoding="utf-8")


def json_text(data: dict[str, Any]) -> str:
    return json.dumps(data, ensure_ascii=False, indent=2) + "\n"


def yaml_doc(*lines: str) -> str:
    return "\n".join(lines).rstrip() + "\n"


def scaffold(ip_path: Path, *, force: bool = False, owner: str = "unassigned") -> dict[str, Any]:
    ip_name = slug(ip_path.name)
    if ip_path.name != ip_name and not ip_path.exists():
        ip_path = ip_path.parent / ip_name
    created_dirs: list[str] = []
    written_files: list[str] = []
    skipped_files: list[str] = []

    for rel in DEFAULT_DIRS:
        path = ip_path / rel
        path.mkdir(parents=True, exist_ok=True)
        created_dirs.append(rel)

    for rel in [
        "ontology/evidence/.gitkeep",
        "req/deep_semantic_intake/.gitkeep",
        "ontology/evidence/stage_runs/.gitkeep",
        "ontology/drafts/.gitkeep",
        "ontology/generated/.gitkeep",
        "ontology/generated/authoring_packets/.gitkeep",
        "ontology/gates/.gitkeep",
        "ontology/metrics/.gitkeep",
        "ontology/runs/.gitkeep",
        "ontology/validations/.gitkeep",
        "knowledge/records/.gitkeep",
        "knowledge/ledger.jsonl",
        "knowledge/views/.gitkeep",
        "knowledge/views/_generated/.gitkeep",
        "knowledge/views/promoted/.gitkeep",
        "handoff/failure_tickets/.gitkeep",
        "sim/waves/.gitkeep",
        "lint/reports/.gitkeep",
        "cdc/.gitkeep",
        "cov/reports/.gitkeep",
        "syn/reports/.gitkeep",
        "syn/netlist/.gitkeep",
    ]:
        touch(ip_path / rel)

    templates = build_templates(ip_name, owner)
    executable_files = {"scripts/run_lint.sh", "scripts/run_sim.sh"}
    for rel, content in templates.items():
        changed = write(ip_path / rel, content, force=force, executable=rel in executable_files)
        (written_files if changed else skipped_files).append(rel)

    graph = build_seed_graph(ip_name)
    changed = write(ip_path / "ontology" / "graph.json", json_text(graph), force=force)
    (written_files if changed else skipped_files).append("ontology/graph.json")

    index = {
        "schema_version": "ip_knowledge_index.v1",
        "generated_at": now(),
        "ip": ip_name,
        "record_count": 0,
        "records": [],
    }
    changed = write(ip_path / "knowledge" / "_index.json", json_text(index), force=force)
    (written_files if changed else skipped_files).append("knowledge/_index.json")

    manifest = {
        "schema_version": SCHEMA_VERSION,
        "generated_at": now(),
        "ip": ip_name,
        "path": str(ip_path),
        "directories": created_dirs,
        "written_files": written_files,
        "skipped_files": skipped_files,
    }
    write(ip_path / ".oag_scaffold.json", json_text(manifest), force=True)
    return manifest


def build_templates(ip: str, owner: str) -> dict[str, str]:
    req_id = f"REQ_{ip.upper()}_001"
    obl_id = f"OBL_{ip.upper()}_RESET_KNOWN"
    contract_id = f"CONTRACT_{ip.upper()}_SIM_SCOREBOARD"
    scenario_id = f"SCN_{ip.upper()}_RESET_DEFAULTS"
    scoreboard_row_id = f"EVT_{ip.upper()}_RESET_DEFAULTS"
    return {
        "README.md": yaml_doc(
            f"# {ip}",
            "",
            "Ontology-first hardware IP scaffold.",
            "",
            "- `req/`: human-readable source requirements",
            "- `ontology/`: canonical machine truth for ROCEV objects",
            "- `knowledge/`: event/finding/decision ledger",
            "- `list/`: deterministic filelists for tools",
        ),
        ".gitignore": yaml_doc(
            "sim/waves/*",
            "lint/reports/*",
            "cov/reports/*",
            "syn/reports/*",
            "syn/netlist/*",
            "!*/.gitkeep",
        ),
        "req/locked_truth.md": yaml_doc(
            f"# {ip} Locked Truth",
            "",
            f"- `{req_id}`: Define the primary externally visible behavior for `{ip}`.",
            "",
            "Edit this file before deriving obligations.",
        ),
        "req/requirements.yaml": yaml_doc(
            "schema: ip_requirements.v1",
            f"ip: {ip}",
            "requirements:",
            f"  - id: {req_id}",
            "    status: draft",
            f"    owner: {owner}",
            "    requirement_type: behavioral",
            "    text: Define the primary externally visible behavior.",
            "    source: req/locked_truth.md",
            "    source_refs:",
            "      - req/locked_truth.md",
            "    source_claim_refs:",
            f"      - CLAIM_{ip.upper()}_PRIMARY_INTENT",
            "    decision_refs:",
            f"      - DEC_{ip.upper()}_RESET_BOUNDARY",
            "    verification_method:",
            "      - scoreboard",
            "    ambiguity_status: ambiguous",
            "    obligations:",
            f"      - {obl_id}",
        ),
        "req/deep_semantic_intake/README.md": yaml_doc(
            f"# {ip} Deep Semantic Intake",
            "",
            "Store interview rounds, source notes, layer worksheets, and hidden implementation implications here.",
            "",
            "Draft notes are not locked truth. Promote only through OAG source claims, ambiguity register, decision matrix, requirements, and lock readiness checks.",
        ),
        "req/source_claims.yaml": yaml_doc(
            "schema_version: oag_source_claims.v1",
            f"ip: {ip}",
            "claims:",
            f"  - id: CLAIM_{ip.upper()}_PRIMARY_INTENT",
            "    source: req/locked_truth.md",
            "    quote: Define the primary externally visible behavior.",
            "    summary: Scaffold placeholder for the first load-bearing user or spec intent.",
            "    status: draft",
            "    normalized_meaning: Primary externally visible behavior remains undefined until user/spec intake resolves it.",
            "    affected_layers:",
            "      - requirements",
            "      - requirement_atoms",
            "      - verification",
            "    requirement_refs:",
            f"      - {req_id}",
            "    decision_refs:",
            f"      - DEC_{ip.upper()}_RESET_BOUNDARY",
            "    ambiguity_refs:",
            f"      - AMB_{ip.upper()}_RESET_BOUNDARY",
        ),
        "req/ambiguity_register.yaml": yaml_doc(
            "schema_version: oag_ambiguity_register.v1",
            f"ip: {ip}",
            "ambiguities:",
            f"  - id: AMB_{ip.upper()}_RESET_BOUNDARY",
            "    question: What concrete reset signal, polarity, timing, and observable default state define the first lock scope?",
            "    status: open",
            "    lock_required: true",
            f"    owner: {owner}",
            "    resolution: null",
            "    waiver_reason: null",
            "    source_claim_refs:",
            f"      - CLAIM_{ip.upper()}_PRIMARY_INTENT",
            "    decision_refs:",
            f"      - DEC_{ip.upper()}_RESET_BOUNDARY",
            "    affects:",
            "      - requirements",
            "      - requirement_atoms",
            "      - obligations",
            "      - contracts",
            "      - verification",
        ),
        "req/evidence_plan.yaml": yaml_doc(
            "schema: ip_evidence_plan.v1",
            f"ip: {ip}",
            "planned_scenarios:",
            f"  - id: {scenario_id}",
            f"    obligations: [{obl_id}]",
            f"    contracts: [{contract_id}]",
            "    expected_scoreboard_rows:",
            f"      - {scoreboard_row_id}",
            "    expected_source:",
            "      kind: behavior_model",
            "      refs:",
            "        - behavior_model.seed_obligations.reset_known_state",
            "contracts:",
            f"  - id: {contract_id}",
            f"    obligation: {obl_id}",
            "    method: scoreboard",
            "    pass_condition: sim/results.xml has zero failures and scoreboard_events.jsonl rows conform to scoreboard_rows.v1 with zero failed rows",
            f"    scenario_refs: [{scenario_id}]",
            f"    scoreboard_row_refs: [{scoreboard_row_id}]",
            "    evidence:",
            "      files:",
            "        - sim/results.xml",
            "        - sim/scoreboard_events.jsonl",
            "      schemas:",
            "        - ontology/evidence/scoreboard_rows.v1.yaml",
        ),
        "ontology/ip.yaml": yaml_doc(
            "schema: ip_object.v1",
            f"id: {ip}",
            f"name: {ip}",
            f"owner: {owner}",
            "status: draft",
            f"created_at: {now()}",
            "stages:",
            "  - req",
            "  - rtl",
            "  - tb",
            "  - sim",
            "  - lint",
            "  - cov",
            "  - formal",
            "  - syn",
            "  - signoff",
        ),
        "ontology/scope_lock.json": json_text(
            {
                "schema_version": "oag_scope_lock.v1",
                "ip": ip,
                "state": "draft",
                "summary": "Initial scaffold is draft-only. User must lock scope before canonical ontology enrichment, RTL, TB, or closure.",
                "confirmed_scope": [],
                "open_questions": [
                    "Confirm product scope before implementation.",
                ],
                "created_at": now(),
            }
        ),
        "ontology/requirements.yaml": yaml_doc(
            "schema: ontology_requirements.v1",
            f"ip: {ip}",
            "requirements:",
            f"  - id: {req_id}",
            "    source: req/locked_truth.md",
            "    source_refs:",
            "      - req/locked_truth.md",
            "      - req/source_claims.yaml",
            "    source_claim_refs:",
            f"      - CLAIM_{ip.upper()}_PRIMARY_INTENT",
            "    decision_refs:",
            f"      - DEC_{ip.upper()}_RESET_BOUNDARY",
            "    status: draft",
            "    requirement_type: behavioral",
            "    verification_method:",
            "      - scoreboard",
            "    ambiguity_status: ambiguous",
            "    text: Define the primary externally visible behavior.",
        ),
        "ontology/requirement_atoms.yaml": yaml_doc(
            "schema_version: oag_requirement_atoms.v1",
            f"ip: {ip}",
            "policy:",
            "  status: draft",
            "  purpose: Semantic decomposition layer between requirement statements and obligations.",
            "  lock_gate: complete requirement atoms before post-lock RTL, TB, or closure claims.",
            "requirement_atoms:",
            f"  - id: ATOM_{ip.upper()}_RESET_KNOWN",
            f"    source_requirement_id: {req_id}",
            "    status: draft",
            "    normalized_text: Reset/default externally visible behavior must be specified before implementation.",
            "    pattern:",
            "      trigger: reset/default observation point is defined",
            "      condition: TBD by locked requirement",
            "      response: all externally visible reset/default state is known",
            "      timing: TBD by locked requirement",
            "      exception: TBD",
            "    boundary:",
            "      responsible_agent: dut",
            "      environment_agents: []",
            "    assumptions:",
            "      environment: []",
            "      dut:",
            "        - DUT owns externally visible reset/default state.",
            "    phenomena:",
            "      monitored_variables: []",
            "      controlled_variables:",
            "        - reset/default externally visible state",
            "      dut_inputs: []",
            "      dut_outputs: []",
            "      controlled_state: []",
            "      observable_outputs:",
            "        - reset/default observation evidence",
            "    ambiguity:",
            "      missing_terms:",
            "        - concrete reset signal and polarity",
            "        - observation cycle",
            "        - externally visible reset/default outputs or registers",
            "      open_questions:",
            "        - What externally visible state must be known after reset?",
        ),
        "ontology/decision_matrix.yaml": yaml_doc(
            "schema_version: oag_decision_matrix.v1",
            f"ip: {ip}",
            "policy:",
            "  status: draft",
            "  purpose: Record product/design decisions that must be resolved before lock-ready implementation.",
            "  lock_gate: lock_required decisions must be decided or waived before post-lock RTL, TB, or closure work.",
            "decisions:",
            f"  - id: DEC_{ip.upper()}_RESET_BOUNDARY",
            "    question: What concrete reset signal, polarity, timing, and observable default state define the first lock scope?",
            "    status: unresolved",
            "    lock_required: true",
            f"    owner: {owner}",
            "    recommended: null",
            "    decision: null",
            "    rationale: Scaffold seed cannot infer reset/default product semantics.",
            "    affects:",
            "      - requirements",
            "      - requirement_atoms",
            "      - obligations",
            "      - contracts",
            "      - verification",
            "    refs:",
            "      - ontology/requirement_atoms.yaml",
        ),
        "ontology/obligations.yaml": yaml_doc(
            "schema: ontology_obligations.v1",
            f"ip: {ip}",
            "obligations:",
            f"  - id: {obl_id}",
            f"    requirement: {req_id}",
            "    status: open",
            "    text: Reset/default observable state is known and mechanically checkable.",
            f"    contracts: [{contract_id}]",
        ),
        "ontology/contracts.yaml": yaml_doc(
            "schema: ontology_contracts.v1",
            f"ip: {ip}",
            "contracts:",
            f"  - id: {contract_id}",
            f"    obligation: {obl_id}",
            "    contract_type: behavioral",
            "    method: scoreboard",
            "    pass_condition: simulator-independent scoreboard rows prove expected vs DUT-observed behavior",
            "    behavior_refs:",
            "      - behavior_model.seed_obligations.reset_known_state",
            "    cycle_rule_refs:",
            "      - cycle_rules.reset.reset_observable_on",
            f"    scenario_refs: [{scenario_id}]",
            f"    scoreboard_row_refs: [{scoreboard_row_id}]",
            "    evidence_kinds: [simulation, scoreboard]",
            "    evidence_schemas: [scoreboard_rows.v1]",
            "    implementation_policy: TB language and simulator are not fixed by this contract",
        ),
        "ontology/modeling.yaml": yaml_doc(
            "schema_version: oag_modeling.v1",
            f"ip: {ip}",
            "modeling_policy:",
            "  profile: simple_leaf_apb_peripheral",
            "  full_fl_model_required: false",
            "  full_cl_model_required: false",
            "  behavior_model_required_for_behavioral_closure: true",
            "  cycle_rules_required_for_temporal_closure: true",
            "  scoreboard_trace_required_for_closure: true",
            "behavior_model:",
            "  seed_obligations:",
            "    reset_known_state:",
            f"      requirement: {req_id}",
            f"      obligation: {obl_id}",
            "      rule: Reset/default observable state must be specified before this obligation can close.",
            "cycle_rules:",
            "  reset:",
            "    reset_observable_on:",
            "      rule: Reset/default observations must be sampled at a contract-defined stable point.",
            "approved_equivalent_oracles: []",
        ),
        "ontology/domain_intent.yaml": yaml_doc(
            "schema_version: oag_domain_intent.v1",
            f"ip: {ip}",
            "policy:",
            "  profile: simple_leaf_peripheral",
            "  development_static_check_required: true",
            "  release_requires_static_or_formal_cdc_rdc: true",
            "clock_domains: []",
            "reset_domains: []",
            "async_inputs: []",
            "cdc_crossings: []",
            "rdc_crossings:",
            "  - id: RDC_UNCLASSIFIED",
            "    classification: no_known_rdc",
            "    basis:",
            "      - scaffold has no declared reset domains yet",
            "    caveat:",
            "      - async reset assertion/deassertion policy must be recorded when reset domains are declared",
            "sync_structures: []",
            "notes:",
            "  - Domain intent is design truth for clocks, resets, async inputs, CDC crossings, and RDC crossings.",
            "  - RTL may implement crossing safety, but RTL must not invent crossing intent.",
        ),
        "ontology/tb_methodology.yaml": yaml_doc(
            "schema_version: oag_tb_methodology.v1",
            f"ip: {ip}",
            "methodology_policy:",
            "  profile: simple_leaf_apb_peripheral",
            "  framework_required: false",
            "  full_uvm_required: false",
            "  default_depth: directed_table_driven_micro_tb",
            "  random_requires_constraints: true",
            "  random_requires_coverage_goals: true",
            "  failed_tests_count_for_coverage: false",
            "  special_domain_sim_only_closure_allowed: false",
            "architecture_roles:",
            "  driver:",
            "    status: planned",
            "    responsibility: drive legal and negative stimulus from scenario intent",
            "  monitor:",
            "    status: planned",
            "    responsibility: observe DUT-facing signals or transactions",
            "  predictor:",
            "    status: planned",
            "    responsibility: compute expected from behavior_model, cycle_rules, or approved oracle",
            "  scoreboard:",
            "    status: planned",
            "    responsibility: emit scoreboard_rows.v1 compare rows",
            "  coverage:",
            "    status: planned",
            "    responsibility: record contract-linked coverage for passing checks",
            "  assertion_hooks:",
            "    status: optional",
            "    responsibility: capture local protocol, temporal, reset, or invariant rules",
            "  result_writer:",
            "    status: planned",
            "    responsibility: emit sim/results.xml, sim/scenario_mapping.json, sim/scoreboard_events.jsonl, and cov/coverage.json when in scope",
            "stimulus_strategy:",
            "  directed_smoke: true",
            "  table_driven_register_tests: true",
            "  constrained_random:",
            "    enabled: false",
            "    constraints: []",
            "    seed_strategy: TBD",
            "coverage_goals:",
            "  - id: COV_INC",
            f"    requirement: {req_id}",
            f"    obligation: {obl_id}",
            f"    contract: {contract_id}",
            "    description: Seed coverage goal for the scaffold reset/default scoreboard scenario.",
            "assertion_candidates: []",
            "formal_candidates: []",
            "notes:",
            "  - TB methodology is profile-scaled and framework-neutral.",
            "  - UVM, cocotb, SV, Verilog, OSVVM, UVVM, or simulator adapters are choices, not truth.",
            "  - Failed tests and failed scoreboard rows must not contribute to closure coverage.",
        ),
        "ontology/verification_plan.yaml": yaml_doc(
            "schema_version: oag_verification_plan.v1",
            f"ip: {ip}",
            "strategy_policy:",
            "  owner_role: oag-verification-strategy-agent",
            "  tb_writer_may_define_strategy: false",
            "  canonical_tb_methodology_file: ontology/tb_methodology.yaml",
            "  coverage_model_split_pending: true",
            "verification_objectives:",
            "  - id: VOBJ_RESET_KNOWN_STATE",
            "    status: draft",
            f"    requirement: {req_id}",
            f"    obligation: {obl_id}",
            f"    contract: {contract_id}",
            "    intent: Prove reset/default observable state once the reset semantics are locked.",
            "    proof_methods: [directed_sim, scoreboard]",
            f"    scenarios: [{scenario_id}]",
            "    negative_scenarios: []",
            "    coverage_goals: [COV_INC]",
            "    assertion_candidates: []",
            "    formal_candidates: []",
            "    fault_models: []",
            "    residual_risks:",
            "      - id: RISK_RESET_SEMANTICS_DRAFT",
            "        risk: Reset/default semantics are draft until ambiguity and decision rows are resolved.",
            "        status: open",
            "open_strategy_blockers:",
            "  - Resolve draft requirement ambiguity before marking verification objectives ready.",
        ),
        "ontology/structure.yaml": yaml_doc(
            "schema: oag_structure_namespace.v1",
            f"ip: {ip}",
            "clock_domains: []",
            "reset_domains: []",
            "signals: []",
            "interfaces: []",
            "registers: []",
            "state: []",
            "derived_signals: []",
            "notes:",
            "  - Structure is the single namespace for ports, registers, state, events, and derived signals.",
            "  - Contracts and modules reference structure ids instead of redeclaring names and widths.",
        ),
        "ontology/decomposition.yaml": yaml_doc(
            "schema: oag_decomposition.v1",
            f"ip: {ip}",
            "profile:",
            "  mode: small_leaf_single_file",
            "  rationale: Seed scaffold uses one leaf RTL file until complexity or reuse requires module decomposition.",
            "  source: ontology/policies.yaml#structure_policy",
            "modules:",
            f"  - id: {ip}",
            f"    name: {ip}",
            "    role: top",
            "    ownership: current_ip",
            f"    file: rtl/{ip}.sv",
            "    implementation_style: small_leaf_single_file",
            f"    owned_obligations: [{obl_id}]",
            f"    owned_contracts: [{contract_id}]",
            "    structure_refs: []",
            "    source_refs: [ontology/requirements.yaml, ontology/obligations.yaml, ontology/contracts.yaml]",
            "    edit_policy: editable",
            "    notes: Replace this with greenfield_modular, legacy_preserve, or wrapper_adapter when the IP shape is known.",
            "interfaces: []",
            "legacy_sources: []",
        ),
        "ontology/design_rules.yaml": yaml_doc(
            "schema: oag_design_rules.v1",
            f"ip: {ip}",
            "rules:",
            "  - id: RULE_REQUIREMENT_SEMANTIC_ATOMS",
            "    kind: requirement_semantic_atoms",
            "    status: active",
            "    severity: block",
            "    text: Locked requirements must decompose into requirement atoms before closure-grade obligations or contracts are used.",
            "    applies_when: scope is locked, canonical ontology is promoted, or closure is claimed",
            "    requires: [requirement, requirement_atom, trigger, response, boundary, phenomena, ambiguity_status]",
            "  - id: RULE_REQUIREMENT_QUALITY_GATE",
            "    kind: requirement_quality_gate",
            "    status: active",
            "    severity: block",
            "    text: Lock-ready requirements must trace to source claims, clear or waive ambiguity, name type, and name verification method.",
            "    applies_when: scope is locked, canonical ontology is promoted, RTL/TB/verification work is dispatched, or closure is claimed",
            "    requires: [source_claim, ambiguity_register, requirement_type, source_refs, verification_method, ambiguity_status]",
            "  - id: RULE_DECISION_MATRIX_LOCK_READINESS",
            "    kind: decision_matrix_lock_readiness",
            "    status: active",
            "    severity: block",
            "    text: Lock-required decisions must be decided or waived before post-lock implementation and closure work.",
            "    applies_when: scope is locked, canonical ontology is promoted, RTL/TB/verification work is dispatched, or closure is claimed",
            "    requires: [decision_matrix, lock_required, status, decision_or_waiver, owner]",
            "  - id: RULE_ASSUME_GUARANTEE_CONTRACT",
            "    kind: assume_guarantee_contract",
            "    status: active",
            "    severity: block",
            "    text: Closure-grade contracts must separate environment assumptions from DUT guarantees.",
            "    applies_when: behavioral, temporal, protocol, CSR, interrupt, ordering, reset, backpressure, or error contracts support closure",
            "    requires: [contract, assume, guarantee, variables, oracle]",
            "  - id: RULE_EVENT_STATE_COMMIT_CONSISTENCY",
            "    kind: event_state_commit_consistency",
            "    status: active",
            "    severity: signoff_block",
            "    text: Side-effect events and their state updates must use the same effective commit condition.",
            "    applies_when: interrupts, status bits, FSM transitions, counters, FIFOs, or handshakes produce side effects",
            "    requires: [event, state_update, commit_condition, contract]",
            "  - id: RULE_SAME_CYCLE_PRIORITY_DECLARED",
            "    kind: same_cycle_priority_declared",
            "    status: active",
            "    severity: signoff_block",
            "    text: Same-cycle conflicts must name the winning action in requirement truth.",
            "    applies_when: software writes, hardware updates, clears, sets, enables, disables, or terminal events can collide",
            "    requires: [conflict, priority, requirement, obligation, contract]",
            "  - id: RULE_SCOREBOARD_ROWS_V1",
            "    kind: scoreboard_evidence_schema",
            "    status: active",
            "    severity: block",
            "    text: Scoreboard evidence must use DUT-facing scoreboard_rows.v1 rows.",
            "    applies_when: expected-versus-observed evidence is submitted",
            "    requires: [goal_id, scenario_id, stimulus, expected, observed, observed_source, passed, mismatch, coverage_refs]",
            "  - id: RULE_CONTRACT_TO_PROOF_COVERAGE",
            "    kind: contract_to_proof_coverage",
            "    status: active",
            "    severity: signoff_block",
            "    text: A contract may only claim a proof scope that is backed by matching assertion, scoreboard, formal, coverage, or log evidence.",
            "    applies_when: any obligation is claimed closed",
            "    requires: [contract, proof_scope, evidence_ref]",
            "  - id: RULE_FAULT_MODEL_COVERAGE",
            "    kind: fault_model_coverage",
            "    status: active",
            "    severity: signoff_block",
            "    text: A load-bearing coverage point should name the requirement fault models it is meant to catch and, for signoff-grade claims, attach killed mutation evidence.",
            "    applies_when: coverage_refs are used as closure evidence for a requirement or obligation",
            "    requires: [requirement, obligation, contract, coverage_refs, fault_models, mutation_results]",
            "  - id: RULE_VERIFICATION_ROLE_DECOMPOSITION",
            "    kind: verification_role_decomposition",
            "    status: active",
            "    severity: signoff_block",
            "    text: Signoff-grade verification should separate UVM-style roles without requiring a specific TB framework.",
            "    applies_when: a testbench architecture is used as closure or signoff evidence",
            "    required_roles: [sequence, driver, monitor, reference_model, scoreboard, coverage, env, test]",
            "    requires: [requirement, obligation, contract, style, framework, roles, independence]",
            "  - id: RULE_TB_METHODOLOGY_KERNEL",
            "    kind: tb_methodology_kernel",
            "    status: active",
            "    severity: block",
            "    text: TB closure evidence must use a profile-appropriate verification methodology without requiring a specific framework.",
            "    applies_when: TB, simulation, scoreboard, coverage, assertion, formal, or scenario evidence is used for closure",
            "    requires: [scenario_intent, driver_or_bfm, monitor, independent_predictor, scoreboard, coverage_strategy, result_writer]",
            "  - id: RULE_VERIFICATION_STRATEGY_OWNS_PROOF",
            "    kind: verification_strategy_owns_proof",
            "    status: active",
            "    severity: block",
            "    text: Verification strategy must define objectives, proof methods, scenarios, coverage goals, and residual risk before TB implementation satisfies them.",
            "    applies_when: locked TB, sim, scoreboard, coverage, assertion, formal, or closure evidence is planned or dispatched",
            "    requires: [verification_plan, verification_objective, proof_methods, scenarios, coverage_goals, residual_risks]",
            "  - id: RULE_CONTRACT_STRENGTH",
            "    kind: contract_strength",
            "    status: active",
            "    severity: block",
            "    text: Implementation-ready contracts must separate assume/guarantee, name variables, resolve oracle refs, and project proof scenarios or properties.",
            "    applies_when: scope is locked, RTL/TB authoring packets are generated, validation is run, or closure is claimed",
            "    requires: [contract, variables, assume, guarantee, oracle, proof_projection]",
            "  - id: RULE_ROLE_SPECIFIC_AUTHORING_PACKETS",
            "    kind: authoring_packet_role_projection",
            "    status: active",
            "    severity: block",
            "    text: RTL and TB agents must consume role-specific authoring packets generated from OAG truth, not independently reinterpret original prose.",
            "    applies_when: RTL or TB native subagent dispatch is prepared",
            "    requires: [rtl_authoring_packet, tb_authoring_packet, contract_refs, expected_source_policy]",
            "  - id: RULE_TRACE_GRAPH_ID_GOVERNANCE",
            "    kind: trace_graph_id_governance",
            "    status: active",
            "    severity: block",
            "    text: Load-bearing source claims, requirements, atoms, obligations, contracts, scenarios, scoreboard rows, and coverage goals must form an unbroken trace graph.",
            "    applies_when: scope is locked, evidence is validated, gate review is run, or closure is claimed",
            "    requires: [source_claim, requirement, requirement_atom, obligation, contract, scenario, evidence]",
            "  - id: RULE_CDC_CROSSING_COVERAGE",
            "    kind: cdc_crossing_coverage",
            "    status: active",
            "    severity: signoff_block",
            "    text: Clock/reset-domain crossing claims must name domains/crossings and attach CDC/RDC review or tool evidence.",
            "    applies_when: SSOT clock_reset_domains, cdc_requirements, or rdc_requirements are load-bearing closure facts",
            "    requires: [requirement, obligation, contract, clock_domains_or_crossings, evidence_refs]",
            "  - id: RULE_PROTOCOL_COMPLIANCE",
            "    kind: protocol_compliance",
            "    status: active",
            "    severity: signoff_block",
            "    text: Interface protocol claims such as AXI/APB/streaming handshakes must be backed by assertion, monitor, VIP, or protocol scoreboard evidence.",
            "    applies_when: an interface protocol is used as a design or integration closure claim",
            "    requires: [requirement, obligation, contract, protocol, evidence_refs]",
            "  - id: RULE_TIMING_CLOSURE",
            "    kind: timing_closure",
            "    status: active",
            "    severity: signoff_block",
            "    text: STA/timing closure claims must name target frequency or target clocks, derive SDC from those clocks plus CDC policy, and cite timing reports with setup/hold status.",
            "    applies_when: timing.target_clocks, timing.sta_expectations, SDC, syn, sta, or sta-post evidence is used for closure",
            "    requires: [requirement, obligation, contract, target_clocks_or_target_frequency, sdc_refs, timing_reports, evidence_refs]",
            "    default_io_delay_ratio: 0.5",
            "  - id: RULE_FUNCTIONAL_COVERAGE_CLOSURE",
            "    kind: functional_coverage_closure",
            "    status: active",
            "    severity: signoff_block",
            "    text: Functional coverage closure must tie coverage goals to observed coverage refs and coverage reports.",
            "    applies_when: coverage_functional, coverage_ssot, coverage.json, or scoreboard coverage refs are used as closure evidence",
            "    requires: [requirement, obligation, contract, coverage_refs, coverage_goal, coverage_actual, evidence_refs]",
            "  - id: RULE_RESET_XPROP_COVERAGE",
            "    kind: reset_xprop_coverage",
            "    status: active",
            "    severity: signoff_block",
            "    text: Reset and X-propagation closure must name reset scenarios or X-prop checks and attach observed evidence.",
            "    applies_when: reset behavior, async assert/sync deassert, reset-domain behavior, or X-prop robustness is load-bearing",
            "    requires: [requirement, obligation, contract, reset_scenarios_or_xprop_checks, coverage_refs, evidence_refs]",
            "  - id: RULE_MODULE_FILE_BOUNDARY",
            "    kind: module_file_boundary",
            "    status: active",
            "    severity: block",
            "    text: Greenfield modular IPs should map each current_ip module to a unique RTL file; shared files require explicit rationale.",
            "    applies_when: decomposition profile is greenfield_modular",
            "    requires: [module, file, ownership, shared_file_rationale_for_exception]",
            "  - id: RULE_RTL_LANGUAGE_SUBSET",
            "    kind: rtl_language_subset",
            "    status: active",
            "    severity: block",
            "    text: Generated RTL may use logic and Verilog generate for static elaboration; procedural loops remain forbidden outside generate blocks.",
            "    applies_when: RTL is authored, generated, repaired, linted, or promoted",
            "    allowed_constructs: [logic, generate, genvar, generate_for]",
            "    forbidden_constructs: [procedural_for, procedural_while, procedural_repeat, procedural_forever, always_ff, always_comb, always_latch, package, import, interface, modport, typedef, enum, struct, class, assertions, covergroups]",
            "    requires: [rtl_compile_report, language_policy]",
            "instances:",
            "  - id: TEMPLATE_EVENT_STATE_COMMIT",
            "    rule: RULE_EVENT_STATE_COMMIT_CONSISTENCY",
            "    status: template",
            "    note: Activate when this IP has side-effect events such as interrupts, status bits, FSM transitions, or terminal ticks.",
            "  - id: TEMPLATE_SAME_CYCLE_PRIORITY",
            "    rule: RULE_SAME_CYCLE_PRIORITY_DECLARED",
            "    status: template",
            "    note: Activate for pairs such as clear-vs-set, write-vs-hardware-update, enable-vs-terminal-tick, or reset-vs-valid.",
            "  - id: TEMPLATE_CONTRACT_PROOF_COVERAGE",
            "    rule: RULE_CONTRACT_TO_PROOF_COVERAGE",
            "    status: template",
            "    note: Activate when a contract is promoted beyond draft or claims formal/assertion coverage.",
            "  - id: TEMPLATE_FAULT_MODEL_COVERAGE",
            "    rule: RULE_FAULT_MODEL_COVERAGE",
            "    status: template",
            "    note: Activate when a coverage point is used as load-bearing closure evidence and should be tied to killed requirement-relevant mutants.",
            "  - id: TEMPLATE_VERIFICATION_ROLE_DECOMPOSITION",
            "    rule: RULE_VERIFICATION_ROLE_DECOMPOSITION",
            "    status: template",
            "    note: Activate for signoff-grade TB architecture; use UVM concepts such as sequence, driver, monitor, reference model, scoreboard, coverage, env, and test without requiring UVM itself.",
            "  - id: TEMPLATE_TB_METHODOLOGY_KERNEL",
            "    rule: RULE_TB_METHODOLOGY_KERNEL",
            "    status: template",
            "    note: Activate when TB evidence is used for closure; choose directed, table-driven, transaction-based, random, assertion-assisted, formal-candidate, or PSS-style depth by IP profile.",
            "  - id: TEMPLATE_CDC_CROSSING_COVERAGE",
            "    rule: RULE_CDC_CROSSING_COVERAGE",
            "    status: template",
            "    note: Activate when SSOT clock_reset_domains/cdc_requirements/rdc_requirements make crossing safety a closure claim.",
            "  - id: TEMPLATE_PROTOCOL_COMPLIANCE",
            "    rule: RULE_PROTOCOL_COMPLIANCE",
            "    status: template",
            "    note: Activate for AXI, APB, streaming, valid/ready, or other interface protocol compliance closure.",
            "  - id: TEMPLATE_TIMING_CLOSURE",
            "    rule: RULE_TIMING_CLOSURE",
            "    status: template",
            "    note: Activate when SDC, STA, syn, or sta-post reports are part of closure or signoff evidence. Use target_clocks or target_frequency_mhz to derive create_clock; derive async clock groups or CDC exceptions from CDC/RDC facts; default input/output delay ratio is 0.5 of clock period unless the IP overrides it.",
            "  - id: TEMPLATE_FUNCTIONAL_COVERAGE_CLOSURE",
            "    rule: RULE_FUNCTIONAL_COVERAGE_CLOSURE",
            "    status: template",
            "    note: Activate when coverage_functional, coverage_ssot, or coverage refs are used to close requirements.",
            "  - id: TEMPLATE_RESET_XPROP_COVERAGE",
            "    rule: RULE_RESET_XPROP_COVERAGE",
            "    status: template",
            "    note: Activate for reset sequencing, async assert/sync deassert, reset-domain, or X-prop robustness closure.",
        ),
        "ontology/stages.yaml": yaml_doc(
            "schema: oag_stage_contracts.v1",
            f"ip: {ip}",
            "stages:",
            "  - id: req",
            "    owner: human-owner",
            "    inputs: [req/locked_truth.md, req/requirements.yaml, req/source_claims.yaml, req/ambiguity_register.yaml, req/evidence_plan.yaml]",
            "    outputs: [ontology/requirements.yaml, ontology/requirement_atoms.yaml, ontology/decision_matrix.yaml, ontology/obligations.yaml, ontology/contracts.yaml, ontology/modeling.yaml, ontology/domain_intent.yaml, ontology/verification_plan.yaml, ontology/tb_methodology.yaml]",
            "    gate: oag.compile",
            "  - id: rtl",
            "    owner: rtl",
            "    inputs: [ontology/generated/design_truth_graph.json, ontology/modeling.yaml, ontology/domain_intent.yaml, list/rtl.f]",
            "    outputs: [rtl/rtl_compile.json]",
            "    gate: rtl_compile",
            "  - id: tb",
            "    owner: tb",
            "    inputs: [ontology/generated/design_truth_graph.json, ontology/modeling.yaml, ontology/domain_intent.yaml, ontology/verification_plan.yaml, ontology/tb_methodology.yaml, rtl/rtl_compile.json]",
            "    outputs: [sim/scenario_mapping.json, sim/scoreboard_events.jsonl]",
            "    gate: scoreboard_rows.v1",
            "  - id: sim",
            "    owner: sim",
            "    inputs: [rtl/rtl_compile.json, sim/scenario_mapping.json, sim/scoreboard_events.jsonl]",
            "    outputs: [sim/results.xml]",
            "    gate: sim_results",
            "  - id: signoff",
            "    owner: signoff",
            "    inputs: [ontology/generated/design_truth_graph.json, ontology/evidence/stage_runs]",
            "    outputs: [signoff/release.yaml]",
            "    gate: oag.decide.signoff",
        ),
        "ontology/policies.yaml": yaml_doc(
            "schema: oag_policy.v1",
            f"ip: {ip}",
            "closure_profile: development",
            "execution_policy:",
            "  hook_auto_continue_until: all",
            "  stop_hook_max_repeats: 3",
            "graph_policy:",
            "  context_uses_cached_graph: true",
            "  compile_skip_when_fresh: true",
            "  strict_fresh_on: [checkpoint, check, signoff]",
            "requirement_quality_policy:",
            "  canonical_source_claims_file: req/source_claims.yaml",
            "  canonical_ambiguity_register_file: req/ambiguity_register.yaml",
            "  canonical_intake_dir: req/deep_semantic_intake",
            "  require_quality_after_lock: true",
            "  require_source_claims_after_lock: true",
            "  unresolved_lock_ambiguity_blocks_implementation: true",
            "  requirement_ambiguity_must_be_clear_or_waived: true",
            "modeling_policy:",
            "  canonical_modeling_file: ontology/modeling.yaml",
            "  profile: simple_leaf_apb_peripheral",
            "  full_fl_model_required: false",
            "  full_cl_model_required: false",
            "  behavior_model_required_for_behavioral_closure: true",
            "  cycle_rules_required_for_temporal_closure: true",
            "  scoreboard_trace_required_for_closure: true",
            "requirement_decomposition_policy:",
            "  canonical_requirement_atom_file: ontology/requirement_atoms.yaml",
            "  require_atoms_after_lock: true",
            "  require_assume_guarantee_for_closure: true",
            "  shallow_obligations_block_closure: true",
            "  open_questions_keep_draft: true",
            "contract_strength_policy:",
            "  canonical_contract_file: ontology/contracts.yaml",
            "  require_contract_strength_after_lock: true",
            "  require_variables_assume_guarantee_oracle: true",
            "  weak_sim_pass_contract_is_smoke_only: true",
            "decision_matrix_policy:",
            "  canonical_decision_matrix_file: ontology/decision_matrix.yaml",
            "  require_lock_required_decisions_after_lock: true",
            "  unresolved_lock_required_blocks_implementation: true",
            "  proposed_is_not_decided: true",
            "  waived_requires_reason: true",
            "verification_strategy_policy:",
            "  canonical_verification_plan_file: ontology/verification_plan.yaml",
            "  owner_role: oag-verification-strategy-agent",
            "  tb_writer_may_define_strategy: false",
            "  required_before_tb_dispatch_after_lock: true",
            "  objectives_require_rocev_refs: true",
            "  residual_risk_required_after_lock: true",
            "authoring_packet_policy:",
            "  canonical_authoring_packet_dir: ontology/generated/authoring_packets",
            "  rtl_packet_pattern: rtl__*.json",
            "  tb_packet_pattern: tb__*.json",
            "  generated_by: oag.compile",
            "  require_role_packets_before_dispatch: true",
            "traceability_policy:",
            "  require_trace_graph_after_lock: true",
            "  source_to_contract_to_evidence_chain_required: true",
            "  orphan_load_bearing_objects_block_closure: true",
            "domain_crossing_policy:",
            "  canonical_domain_intent_file: ontology/domain_intent.yaml",
            "  profile: simple_leaf_peripheral",
            "  domain_intent_required: true",
            "  async_input_classification_required: true",
            "  synchronizer_structure_required_for_async_inputs: true",
            "  development_static_check_required: true",
            "  full_cdc_tool_required_for_development: false",
            "  full_rdc_tool_required_for_development: false",
            "  release_requires_static_cdc_rdc_or_approved_applicability: true",
            "tb_methodology_policy:",
            "  canonical_tb_methodology_file: ontology/tb_methodology.yaml",
            "  profile: simple_leaf_apb_peripheral",
            "  framework_required: false",
            "  full_uvm_required: false",
            "  random_requires_constraints: true",
            "  random_requires_coverage_goals: true",
            "  coverage_refs_require_goals: true",
            "  failed_tests_count_for_coverage: false",
            "  results_xml_required_after_sim: true",
            "  scenario_mapping_required_after_sim: true",
            "  scoreboard_rows_required_after_sim: true",
            "  special_domain_sim_only_closure_allowed: false",
            "structure_policy:",
            "  default_profile: small_leaf_single_file",
            "  allowed_profiles: [greenfield_modular, small_leaf_single_file, legacy_preserve, wrapper_adapter]",
            "  single_file_allowed_when: small leaf IP with explicit rationale and module ownership",
            "  greenfield_modular_requires: [decomposition, module_ownership, unique_module_files, interface_contracts]",
            "  legacy_preserve_requires: [legacy_sources, preserve_existing_hierarchy]",
            "  wrapper_adapter_requires: [legacy_core, wrapper_module, boundary_contracts]",
            "profiles:",
            "  draft:",
            "    intent: authoring and exploration",
            "    may_claim_signoff: false",
            "  development:",
            "    intent: normal IP development with real evidence",
            "    may_claim_signoff: false",
            "  signoff:",
            "    intent: audit-grade closure",
            "    may_claim_signoff: true",
            "action_policy:",
            "  claim_complete:",
            "    requires: [rocev_chain, explicit_validation_status, closure_matrix, evidence_hash_freshness, append_only_ledger, monotonic_closure, decision_receipt]",
            "  close_obligation:",
            "    requires: [rocev_chain, explicit_validation_status, closure_matrix, evidence_hash_freshness, append_only_ledger, monotonic_closure]",
            "  promote:",
            "    requires: [closed_validation, closure_matrix, decision_receipt, protected_fields_clean, human_review, enterprise_promotion_record]",
            "  signoff:",
            "    requires: [closed_obligations, closure_matrix, decision_receipt, truth_graph_compiled, fresh_stage_receipts, protected_fields_clean, append_only_ledger, monotonic_closure, human_approval]",
            "rtl_policy:",
            "  dialect: oag_sv_lite_v1",
            "  base: verilog_2001",
            "  allowed_extensions: [logic, generate]",
            "  disallowed_constructs: [always_ff, always_comb, typedef, enum, struct, interface, package, class, assertions, covergroups]",
            "ppa_policy:",
            "  mode: ppa_aware_correctness_first",
            "  require_ppa_notes_for_nontrivial_rtl: true",
            "  simple_leaf_peripheral:",
            "    default_strategy:",
            "      performance: single_cycle_simple_decode",
            "      power: explicit_write_enable",
            "      area: no_unnecessary_pipeline_or_duplication",
            "    pipeline_default: false",
            "    clock_gating_default: infer_enable_only",
        ),
        "ontology/protection.yaml": yaml_doc(
            "schema: oag_protection_policy.v1",
            f"ip: {ip}",
            "policy:",
            "  semantic_change_requires: human_approval_or_decision_record",
            "  default_actor: untrusted_ai_client",
            "protected_paths:",
            "  - req/locked_truth.md",
            "  - req/requirements.yaml",
            "  - req/source_claims.yaml",
            "  - req/ambiguity_register.yaml",
            "  - req/evidence_plan.yaml",
            "  - ontology/requirements.yaml",
            "  - ontology/requirement_atoms.yaml",
            "  - ontology/decision_matrix.yaml",
            "  - ontology/obligations.yaml",
            "  - ontology/contracts.yaml",
            "  - ontology/modeling.yaml",
            "  - ontology/domain_intent.yaml",
            "  - ontology/verification_plan.yaml",
            "  - ontology/tb_methodology.yaml",
            "  - ontology/structure.yaml",
            "  - ontology/decomposition.yaml",
            "  - ontology/policies.yaml",
            "protected_fields:",
            "  - requirements[].text",
            "  - requirements[].requirement_type",
            "  - requirements[].source_refs",
            "  - requirements[].source_claim_refs",
            "  - requirements[].decision_refs",
            "  - requirements[].verification_method",
            "  - requirements[].ambiguity_status",
            "  - claims[].quote",
            "  - claims[].summary",
            "  - claims[].normalized_meaning",
            "  - ambiguities[].question",
            "  - ambiguities[].status",
            "  - ambiguities[].resolution",
            "  - ambiguities[].lock_required",
            "  - ambiguities[].waiver_reason",
            "  - requirement_atoms[].normalized_text",
            "  - requirement_atoms[].pattern",
            "  - requirement_atoms[].boundary",
            "  - requirement_atoms[].assumptions",
            "  - requirement_atoms[].phenomena",
            "  - decisions[].question",
            "  - decisions[].status",
            "  - decisions[].decision",
            "  - decisions[].lock_required",
            "  - decisions[].waiver_reason",
            "  - decisions[].rationale",
            "  - obligations[].text",
            "  - obligations[].requirement",
            "  - contracts[].obligation",
            "  - contracts[].method",
            "  - contracts[].pass_condition",
            "  - contracts[].behavior_refs",
            "  - contracts[].cycle_rule_refs",
            "  - contracts[].scenario_refs",
            "  - contracts[].variables",
            "  - contracts[].assume",
            "  - contracts[].guarantee",
            "  - contracts[].oracle",
            "  - contracts[].verification_projection",
            "  - behavior_model",
            "  - cycle_rules",
            "  - modeling_policy",
            "  - domain_crossing_policy",
            "  - tb_methodology_policy",
            "  - methodology_policy",
            "  - architecture_roles",
            "  - stimulus_strategy",
            "  - coverage_goals",
            "  - assertion_candidates",
            "  - formal_candidates",
            "  - clock_domains",
            "  - reset_domains",
            "  - async_inputs",
            "  - cdc_crossings",
            "  - rdc_crossings",
            "  - verification_strategy_policy",
            "  - verification_objectives[].intent",
            "  - verification_objectives[].proof_methods",
            "  - verification_objectives[].scenarios",
            "  - verification_objectives[].coverage_goals",
            "  - verification_objectives[].residual_risks",
            "  - structure_policy",
            "  - profile.mode",
            "  - modules[].ownership",
            "  - modules[].owned_obligations",
            "  - modules[].owned_contracts",
            "  - closure_profile",
            "  - execution_policy",
            "  - graph_policy",
            "  - profiles.signoff",
            "approval_record:",
            "  tool: oag.record",
            "  required_actor_kind: human",
            "  required_type: decision",
        ),
        "ontology/evidence/scoreboard_rows.v1.yaml": yaml_doc(
            "schema: evidence_schema.v1",
            "id: scoreboard_rows.v1",
            "artifact: sim/scoreboard_events.jsonl",
            "format: jsonl",
            "policy:",
            "  tb_implementation: free",
            "  accepted_tb_styles:",
            "    - verilog",
            "    - systemverilog",
            "    - uvm",
            "    - cocotb",
            "    - python",
            "    - simulator_adapter",
            "  fixed_contract: row semantics and required fields",
            "required_fields:",
            "  - goal_id",
            "  - scenario_id",
            "  - cycle",
            "  - stimulus",
            "  - expected",
            "  - observed",
            "  - observed_source",
            "  - passed",
            "  - mismatch",
            "  - coverage_refs",
            "expected_source_kinds:",
            "  - behavior_model",
            "  - cycle_rules",
            "  - fl_model",
            "  - cl_model",
            "  - formal_property",
            "  - golden_vector",
            "  - assertion",
            "  - manual_spec",
            "  - reference_log",
            "  - approved_equivalent_oracle",
            "observed_source_kinds:",
            "  - dut_signal",
            "  - monitor",
            "  - waveform",
            "  - transaction",
            "  - assertion",
            "  - interface_sample",
            "  - bus_monitor",
            "rules:",
            "  - observed_source.kind must describe DUT observation, not a model source",
            "  - observed must be sampled from DUT-facing signals, monitors, waves, transactions, or assertions",
            "  - expected may come from behavior_model, cycle_rules, approved FL/CL, formal property, golden vector, or approved equivalent oracle",
            "  - manual_spec expected_source is provisional smoke/debug evidence only and cannot close an obligation unless linked to a decision receipt or replaced by model/cycle/formal refs",
            "  - approved_equivalent_oracle expected_source requires decision_receipt_id, approver, scope, substitute_artifact, reason_full_model_not_required, and obligations_covered",
            "  - a passing row must not carry a mismatch explanation",
            "  - a failing row must carry a mismatch explanation",
        ),
        "ontology/evidence/stage_run_receipt.v1.yaml": yaml_doc(
            "schema: evidence_schema.v1",
            "id: stage_run_receipt.v1",
            "artifact: ontology/evidence/stage_runs/<stage>.json",
            "format: json",
            "required_fields:",
            "  - stage",
            "  - owner",
            "  - status",
            "  - command",
            "  - actor",
            "  - started_at",
            "  - completed_at",
            "  - input_fingerprints",
            "  - output_fingerprints",
            "freshness_rule: every fingerprint path must exist on disk and sha256 must match current file content",
        ),
        "ontology/evidence/cdc_rdc_report.v1.yaml": yaml_doc(
            "schema: evidence_schema.v1",
            "id: cdc_rdc_report.v1",
            "artifact: cdc/oag_domain_crossing_check.json or signoff CDC/RDC tool report",
            "format: json_or_tool_report",
            "required_fields:",
            "  - schema_version",
            "  - ip",
            "  - status",
            "  - domain_intent",
            "  - evidence_strength",
            "  - clock_domains",
            "  - reset_domains",
            "  - cdc_crossings",
            "  - rdc_crossings",
            "  - issues",
            "rules:",
            "  - development evidence may use lightweight structural checks and functional support scenarios",
            "  - release closure requires static, formal, tool-grade, or approved equivalent evidence",
            "  - simulation-only evidence is not CDC/RDC closure evidence",
        ),
        "ontology/evidence/tb_methodology_report.v1.yaml": yaml_doc(
            "schema: evidence_schema.v1",
            "id: tb_methodology_report.v1",
            "artifact: ontology/tb_methodology.yaml plus TB subagent receipt and sim/cov outputs",
            "format: yaml_json_or_tool_report",
            "required_fields:",
            "  - schema_version",
            "  - methodology_profile",
            "  - architecture_roles",
            "  - stimulus_strategy",
            "  - expected_source_policy",
            "  - coverage_strategy",
            "  - result_artifacts",
            "rules:",
            "  - framework choice is free when evidence semantics are preserved",
            "  - random closure requires constraints and coverage goals",
            "  - failed tests and failed scoreboard rows do not count toward closure coverage",
            "  - ordinary simulation-only evidence does not close CDC/RDC, low-power, safety, or AMS claims",
        ),
        "ontology/evidence/verification_plan_report.v1.yaml": yaml_doc(
            "schema: evidence_schema.v1",
            "id: verification_plan_report.v1",
            "artifact: ontology/verification_plan.yaml plus strategy subagent receipt",
            "format: yaml_json_or_tool_report",
            "required_fields:",
            "  - schema_version",
            "  - verification_objectives",
            "  - proof_methods",
            "  - scenarios",
            "  - coverage_goals",
            "  - residual_risks",
            "rules:",
            "  - strategy defines proof objectives; TB implementation satisfies them",
            "  - locked TB work requires objectives that map to requirement, obligation, and contract refs",
        ),
        "ontology/evidence/formal_assertion_report.v1.yaml": yaml_doc(
            "schema: evidence_schema.v1",
            "id: formal_assertion_report.v1",
            "artifact: signoff/formal_assertion_report.json",
            "format: json",
            "required_fields:",
            "  - schema_version",
            "  - ip",
            "  - status",
            "  - closure_profile",
            "  - method",
            "  - checks",
            "  - properties",
            "  - issues",
            "  - signoff_limitations",
            "  - evidence_refs",
            "rule: status=development_pass is development evidence only; auto research must rank it as partially_closed unless a promoted formal contract and signoff evidence exist",
        ),
        "ontology/metrics/improvement_metrics.v1.yaml": yaml_doc(
            "schema: metrics_schema.v1",
            "id: oag_improvement_metrics.v1",
            "artifact: ontology/metrics/improvement_metrics.json",
            "history: ontology/metrics/improvement_history.jsonl",
            "format: json",
            "scope: generic IP progress measurement; obligation counts are derived from each IP ontology and are not fixed",
            "required_numeric_groups:",
            "  - closure",
            "  - check",
            "  - evidence",
            "  - stage_receipts",
            "  - ledger",
            "  - design",
            "  - auto_research",
            "  - decisions",
            "rule: use oag.metrics after meaningful improvement boundaries so progress can be compared numerically across IPs",
        ),
        "ontology/handoff_readiness.v1.yaml": yaml_doc(
            "schema: action_schema.v1",
            "id: oag_readiness_handoff.v1",
            "artifact: handoff/readiness_handoff.json",
            "history: handoff/readiness_history.jsonl",
            "format: json",
            "scope: generic IP readiness handoff derived from OAG metrics and auto-research reports",
            "required_fields:",
            "  - schema_version",
            "  - numeric_summary",
            "  - readiness",
            "  - ranked_next_actions",
            "  - signoff_blockers",
            "  - evidence_refs",
            "rule: development_ready and signoff_ready must be numerically derived; development closure must not be presented as signoff readiness",
        ),
        "ontology/decision_receipt.v1.yaml": yaml_doc(
            "schema: action_schema.v1",
            "id: oag_decision_receipt.v1",
            "artifact: ontology/validations/<decision_id>.json",
            "format: json",
            "required_fields:",
            "  - id",
            "  - action",
            "  - allowed",
            "  - reason",
            "  - actor",
            "  - evidence",
            "  - ledger_event",
            "rule: completion decisions must be recorded after oag.check/oag.inspect and hash-chained into knowledge/ledger.jsonl",
        ),
        "ontology/run_state.v1.yaml": yaml_doc(
            "schema: action_schema.v1",
            "id: oag_run_state.v1",
            "artifact: ontology/runs/<run_id>/run_state.json",
            "format: json",
            "required_fields:",
            "  - run_id",
            "  - status",
            "  - active_obligation",
            "  - active_contracts",
            "  - next_action",
            "  - last_checkpoint",
            "rule: run state drives one next action but closure remains governed by ROCEV records and decision receipts",
        ),
        "ontology/failure_ticket.v1.yaml": yaml_doc(
            "schema: action_schema.v1",
            "id: failure_ticket.v1",
            "artifact: handoff/failure_tickets/<ticket_id>.json",
            "required_fields:",
            "  - failing_contract",
            "  - owner_workflow",
            "  - expected",
            "  - observed",
            "  - evidence",
            "  - editable_files",
            "  - forbidden_edits",
            "  - required_evidence_after_patch",
            "rule: agents repair one unclosed contract at a time and never edit locked truth",
        ),
        "ontology/gates/gate_self_test_registry.yaml": yaml_doc(
            "schema: oag_gate_self_test_registry.v1",
            f"ip: {ip}",
            "gates:",
            "  - id: scoreboard_rows.v1",
            "    validator: oag.inspect.scoreboard",
            "    status: covered",
            "    positive_fixture: sim/scoreboard_events.jsonl",
            "    mutation_tests: [missing_observed_source, model_observed_source, empty_observed]",
            "  - id: design_truth_graph",
            "    validator: oag.compile",
            "    status: covered",
            "    positive_fixture: ontology/requirements.yaml",
            "    mutation_tests: [missing_requirement_id, orphan_obligation, orphan_contract]",
            "  - id: stage_run_receipt.v1",
            "    validator: oag.check.stage_receipts",
            "    status: open",
            "    mutation_tests: [missing_output, fingerprint_mismatch]",
            "  - id: formal_assertion_auto_research",
            "    validator: oag.check.auto_research",
            "    status: covered",
            "    mutation_tests: [development_formal_marked_closed, missing_bounded_limitation, missing_contract_signoff_limitation]",
            "  - id: improvement_metrics",
            "    validator: oag.metrics",
            "    status: covered",
            "    mutation_tests: [metrics_snapshot_missing_history, closure_percent_regression_visibility]",
            "  - id: readiness_handoff",
            "    validator: oag.check.handoff",
            "    status: covered",
            "    mutation_tests: [development_marked_signoff_ready, numeric_summary_mismatch, missing_handoff_evidence_ref]",
            "  - id: protected_fields",
            "    validator: oag.check.protection",
            "    status: covered",
            "    mutation_tests: [unapproved_locked_truth_edit, missing_protection_policy]",
            "  - id: append_only_ledger",
            "    validator: oag.check.ledger",
            "    status: covered",
            "    mutation_tests: [payload_tamper, prev_hash_mismatch, invalid_jsonl]",
            "  - id: monotonic_closure",
            "    validator: oag.check.monotonic",
            "    status: covered",
            "    mutation_tests: [closed_to_open_without_decision]",
            "  - id: module_file_boundary",
            "    validator: oag.compile.decomposition",
            "    status: covered",
            "    mutation_tests: [greenfield_modules_share_file_without_rationale]",
            "  - id: verified_completion",
            "    validator: oag.check.closure_matrix",
            "    status: covered",
            "    mutation_tests: [missing_validation_status, stale_evidence_hash, missing_decision_receipt]",
        ),
        "ontology/actors.yaml": yaml_doc(
            "schema: ontology_actors.v1",
            f"ip: {ip}",
            "actors:",
            "  - id: human-owner",
            "    kind: human",
            f"    owner: {owner}",
            "  - id: codex",
            "    kind: ai",
            "    surface: cli",
        ),
        "ontology/actions.yaml": yaml_doc(
            "schema: ontology_actions.v1",
            f"ip: {ip}",
            "actions: []",
        ),
        "list/rtl.f": yaml_doc("+incdir+rtl", "rtl/*.sv"),
        "list/tb.f": yaml_doc("+incdir+tb", "tb/*.sv", "tb/cocotb/*.py"),
        "list/sim.f": yaml_doc("-f list/rtl.f", "-f list/tb.f"),
        "list/lint.f": yaml_doc("-f list/rtl.f"),
        "list/syn.f": yaml_doc("-f list/rtl.f"),
        "doc/design.md": yaml_doc(
            f"# {ip} Design",
            "",
            "## Intent",
            "",
            "## Interfaces",
            "",
            "## State",
            "",
            "## Reset Behavior",
        ),
        "doc/verification.md": yaml_doc(
            f"# {ip} Verification",
            "",
            "## Contracts",
            f"- `{contract_id}`",
            "",
            "## Scoreboard Evidence",
            "- TB implementation is free: Verilog, SystemVerilog, UVM, Python, cocotb, or simulator adapter.",
            "- The submitted evidence row schema is fixed: `ontology/evidence/scoreboard_rows.v1.yaml`.",
            "",
            "## Methodology",
            "- Methodology intent lives in `ontology/tb_methodology.yaml`.",
            "- The TB should choose the smallest sufficient method for the IP profile.",
            "- Random evidence needs constraints and coverage goals before closure.",
            "- Failed rows do not count toward closure coverage.",
            "",
            "## Evidence",
            "- sim/results.xml",
            "- sim/scoreboard_events.jsonl",
        ),
        "doc/signoff.md": yaml_doc(
            f"# {ip} Signoff",
            "",
            "Do not sign off until OAG decide allows `claim_complete`.",
            "",
            "Signoff must keep protected fields clean, ledger hash-chain valid, and closed objects monotonic.",
        ),
        "scripts/run_sim.sh": yaml_doc(
            "#!/usr/bin/env bash",
            "set -euo pipefail",
            "mkdir -p sim",
            "echo 'TODO: connect simulator command for this IP'",
        ),
        "scripts/run_lint.sh": yaml_doc(
            "#!/usr/bin/env bash",
            "set -euo pipefail",
            "IP_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")/..\" && pwd)\"",
            "CODEX_ROOT=\"${OAG_CODEX_ROOT:-}\"",
            "if [ -z \"$CODEX_ROOT\" ]; then",
            "  SEARCH=\"$IP_DIR\"",
            "  while [ \"$SEARCH\" != \"/\" ]; do",
            "    if [ -f \"$SEARCH/.codex/scripts/oag_pyslang_lint.py\" ]; then CODEX_ROOT=\"$SEARCH/.codex\"; break; fi",
            "    SEARCH=\"$(dirname \"$SEARCH\")\"",
            "  done",
            "fi",
            "BACKEND=\"${OAG_LINT_BACKEND:-auto}\"",
            "mkdir -p lint/reports",
            "case \"$BACKEND\" in",
            "  pyslang)",
            "    if [ -z \"$CODEX_ROOT\" ] || [ ! -f \"$CODEX_ROOT/scripts/oag_pyslang_lint.py\" ]; then",
            "      echo \"OAG_LINT_BACKEND=pyslang requires OAG_CODEX_ROOT or a parent .codex with scripts/oag_pyslang_lint.py\" >&2",
            "      exit 2",
            "    fi",
            "    python3 \"$CODEX_ROOT/scripts/oag_pyslang_lint.py\" --ip-dir \"$IP_DIR\" --filelist list/lint.f --out lint/dut_lint.json --json > lint/reports/pyslang_lint.stdout.json",
            "    ;;",
            "  verilator)",
            "    verilator --lint-only -sv -Wno-fatal -f list/lint.f > lint/reports/verilator_lint.stdout.txt 2> lint/reports/verilator_lint.stderr.txt",
            "    python3 - <<'PY'",
            "import json, pathlib",
            "pathlib.Path('lint/dut_lint.json').write_text(json.dumps({'schema_version':'oag_lint.v1','status':'pass','tool':'verilator'}, indent=2)+'\\n')",
            "PY",
            "    ;;",
            "  auto)",
            "    if python3 -c 'import pyslang' >/dev/null 2>&1 && [ -n \"$CODEX_ROOT\" ]; then",
            "      OAG_LINT_BACKEND=pyslang \"$0\"",
            "    elif command -v verilator >/dev/null 2>&1; then",
            "      OAG_LINT_BACKEND=verilator \"$0\"",
            "    else",
            "      echo '{\"schema_version\":\"oag_lint.v1\",\"status\":\"skipped\",\"tool\":\"none\",\"reason\":\"no pyslang or verilator available\"}' > lint/dut_lint.json",
            "    fi",
            "    ;;",
            "  *) echo \"unsupported OAG_LINT_BACKEND=$BACKEND\" >&2; exit 2 ;;",
            "esac",
        ),
        "signoff/release.yaml": yaml_doc(
            "schema: ip_release.v1",
            f"ip: {ip}",
            "status: draft",
            "validations: []",
        ),
    }


def build_seed_graph(ip: str) -> dict[str, Any]:
    req_id = f"REQ_{ip.upper()}_001"
    obl_id = f"OBL_{ip.upper()}_RESET_KNOWN"
    contract_id = f"CONTRACT_{ip.upper()}_SIM_SCOREBOARD"
    return {
        "schema_version": "oag_ontology_graph.v1",
        "generated_at": now(),
        "ip": ip,
        "nodes": [
            {"id": f"ip::{ip}", "type": "ip", "label": ip, "status": "draft"},
            {"id": f"requirement::{req_id}", "type": "requirement", "label": req_id, "status": "draft"},
            {"id": f"obligation::{obl_id}", "type": "obligation", "label": obl_id, "status": "open"},
            {"id": f"contract::{contract_id}", "type": "contract", "label": contract_id, "status": "draft"},
        ],
        "edges": [
            {"source": f"ip::{ip}", "target": f"requirement::{req_id}", "label": "has_requirement"},
            {"source": f"requirement::{req_id}", "target": f"obligation::{obl_id}", "label": "has_obligation"},
            {"source": f"obligation::{obl_id}", "target": f"contract::{contract_id}", "label": "judged_by"},
        ],
    }


def cmd_create(args: argparse.Namespace) -> int:
    manifest = scaffold(Path(args.ip_dir), force=args.force, owner=args.owner)
    print(json.dumps(manifest, ensure_ascii=False, indent=2))
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)
    create = sub.add_parser("create", help="create an ontology-first IP scaffold")
    create.add_argument("ip_dir")
    create.add_argument("--owner", default="unassigned")
    create.add_argument("--force", action="store_true")
    create.set_defaults(func=cmd_create)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
