#!/usr/bin/env python3
"""Create an ontology-first hardware IP scaffold."""

from __future__ import annotations

import argparse
import json
import re
import stat
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


SCHEMA_VERSION = "oag_ip_scaffold.v1"
DEFAULT_DIRS = [
    "req",
    "ontology/evidence",
    "ontology/evidence/stage_runs",
    "ontology/drafts",
    "ontology/generated",
    "ontology/generated/authoring_packets",
    "ontology/gates",
    "ontology/metrics",
    "ontology/runs",
    "ontology/validations",
    "knowledge/records",
    "knowledge/views",
    "knowledge/views/_generated",
    "knowledge/views/promoted",
    "handoff/failure_tickets",
    "rtl",
    "tb/cocotb",
    "sim/waves",
    "lint/reports",
    "cov/reports",
    "formal",
    "syn/reports",
    "syn/netlist",
    "sdc",
    "list",
    "doc",
    "scripts",
    "signoff",
]


def now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def slug(value: str) -> str:
    text = re.sub(r"[^a-zA-Z0-9_]+", "_", value.strip()).strip("_").lower()
    text = re.sub(r"_+", "_", text)
    if not text:
        raise ValueError("IP name cannot be empty")
    if not re.match(r"^[a-zA-Z_][a-zA-Z0-9_]*$", text):
        raise ValueError(f"invalid IP name after normalization: {text}")
    return text


def write(path: Path, content: str, *, force: bool, executable: bool = False) -> bool:
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    if executable:
        mode = path.stat().st_mode
        path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return True


def touch(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        path.write_text("", encoding="utf-8")


def json_text(data: dict[str, Any]) -> str:
    return json.dumps(data, ensure_ascii=False, indent=2) + "\n"


def yaml_doc(*lines: str) -> str:
    return "\n".join(lines).rstrip() + "\n"


def scaffold(ip_path: Path, *, force: bool = False, owner: str = "unassigned") -> dict[str, Any]:
    ip_name = slug(ip_path.name)
    if ip_path.name != ip_name and not ip_path.exists():
        ip_path = ip_path.parent / ip_name
    created_dirs: list[str] = []
    written_files: list[str] = []
    skipped_files: list[str] = []

    for rel in DEFAULT_DIRS:
        path = ip_path / rel
        path.mkdir(parents=True, exist_ok=True)
        created_dirs.append(rel)

    for rel in [
        "ontology/evidence/.gitkeep",
        "ontology/evidence/stage_runs/.gitkeep",
        "ontology/drafts/.gitkeep",
        "ontology/generated/.gitkeep",
        "ontology/generated/authoring_packets/.gitkeep",
        "ontology/gates/.gitkeep",
        "ontology/metrics/.gitkeep",
        "ontology/runs/.gitkeep",
        "ontology/validations/.gitkeep",
        "knowledge/records/.gitkeep",
        "knowledge/ledger.jsonl",
        "knowledge/views/.gitkeep",
        "knowledge/views/_generated/.gitkeep",
        "knowledge/views/promoted/.gitkeep",
        "handoff/failure_tickets/.gitkeep",
        "sim/waves/.gitkeep",
        "lint/reports/.gitkeep",
        "cov/reports/.gitkeep",
        "syn/reports/.gitkeep",
        "syn/netlist/.gitkeep",
    ]:
        touch(ip_path / rel)

    templates = build_templates(ip_name, owner)
    executable_files = {"scripts/run_lint.sh", "scripts/run_sim.sh"}
    for rel, content in templates.items():
        changed = write(ip_path / rel, content, force=force, executable=rel in executable_files)
        (written_files if changed else skipped_files).append(rel)

    graph = build_seed_graph(ip_name)
    changed = write(ip_path / "ontology" / "graph.json", json_text(graph), force=force)
    (written_files if changed else skipped_files).append("ontology/graph.json")

    index = {
        "schema_version": "ip_knowledge_index.v1",
        "generated_at": now(),
        "ip": ip_name,
        "record_count": 0,
        "records": [],
    }
    changed = write(ip_path / "knowledge" / "_index.json", json_text(index), force=force)
    (written_files if changed else skipped_files).append("knowledge/_index.json")

    manifest = {
        "schema_version": SCHEMA_VERSION,
        "generated_at": now(),
        "ip": ip_name,
        "path": str(ip_path),
        "directories": created_dirs,
        "written_files": written_files,
        "skipped_files": skipped_files,
    }
    write(ip_path / ".oag_scaffold.json", json_text(manifest), force=True)
    return manifest


def build_templates(ip: str, owner: str) -> dict[str, str]:
    req_id = f"REQ_{ip.upper()}_001"
    obl_id = f"OBL_{ip.upper()}_RESET_KNOWN"
    contract_id = f"CONTRACT_{ip.upper()}_SIM_SCOREBOARD"
    return {
        "README.md": yaml_doc(
            f"# {ip}",
            "",
            "Ontology-first hardware IP scaffold.",
            "",
            "- `req/`: human-readable source requirements",
            "- `ontology/`: canonical machine truth for ROCEV objects",
            "- `knowledge/`: event/finding/decision ledger",
            "- `list/`: deterministic filelists for tools",
        ),
        ".gitignore": yaml_doc(
            "sim/waves/*",
            "lint/reports/*",
            "cov/reports/*",
            "syn/reports/*",
            "syn/netlist/*",
            "!*/.gitkeep",
        ),
        "req/locked_truth.md": yaml_doc(
            f"# {ip} Locked Truth",
            "",
            f"- `{req_id}`: Define the primary externally visible behavior for `{ip}`.",
            "",
            "Edit this file before deriving obligations.",
        ),
        "req/requirements.yaml": yaml_doc(
            "schema: ip_requirements.v1",
            f"ip: {ip}",
            "requirements:",
            f"  - id: {req_id}",
            "    status: draft",
            f"    owner: {owner}",
            "    text: Define the primary externally visible behavior.",
            "    source: req/locked_truth.md",
            "    obligations:",
            f"      - {obl_id}",
        ),
        "req/evidence_plan.yaml": yaml_doc(
            "schema: ip_evidence_plan.v1",
            f"ip: {ip}",
            "contracts:",
            f"  - id: {contract_id}",
            f"    obligation: {obl_id}",
            "    method: scoreboard",
            "    pass_condition: sim/results.xml has zero failures and scoreboard_events.jsonl rows conform to scoreboard_rows.v1 with zero failed rows",
            "    evidence:",
            "      files:",
            "        - sim/results.xml",
            "        - sim/scoreboard_events.jsonl",
            "      schemas:",
            "        - ontology/evidence/scoreboard_rows.v1.yaml",
        ),
        "ontology/ip.yaml": yaml_doc(
            "schema: ip_object.v1",
            f"id: {ip}",
            f"name: {ip}",
            f"owner: {owner}",
            "status: draft",
            f"created_at: {now()}",
            "stages:",
            "  - req",
            "  - rtl",
            "  - tb",
            "  - sim",
            "  - lint",
            "  - cov",
            "  - formal",
            "  - syn",
            "  - signoff",
        ),
        "ontology/requirements.yaml": yaml_doc(
            "schema: ontology_requirements.v1",
            f"ip: {ip}",
            "requirements:",
            f"  - id: {req_id}",
            "    source: req/locked_truth.md",
            "    status: draft",
            "    text: Define the primary externally visible behavior.",
        ),
        "ontology/obligations.yaml": yaml_doc(
            "schema: ontology_obligations.v1",
            f"ip: {ip}",
            "obligations:",
            f"  - id: {obl_id}",
            f"    requirement: {req_id}",
            "    status: open",
            "    text: Reset/default observable state is known and mechanically checkable.",
            f"    contracts: [{contract_id}]",
        ),
        "ontology/contracts.yaml": yaml_doc(
            "schema: ontology_contracts.v1",
            f"ip: {ip}",
            "contracts:",
            f"  - id: {contract_id}",
            f"    obligation: {obl_id}",
            "    method: scoreboard",
            "    pass_condition: simulator-independent scoreboard rows prove expected vs DUT-observed behavior",
            "    evidence_kinds: [simulation, scoreboard]",
            "    evidence_schemas: [scoreboard_rows.v1]",
            "    implementation_policy: TB language and simulator are not fixed by this contract",
        ),
        "ontology/structure.yaml": yaml_doc(
            "schema: oag_structure_namespace.v1",
            f"ip: {ip}",
            "clock_domains: []",
            "reset_domains: []",
            "signals: []",
            "interfaces: []",
            "registers: []",
            "state: []",
            "derived_signals: []",
            "notes:",
            "  - Structure is the single namespace for ports, registers, state, events, and derived signals.",
            "  - Contracts and modules reference structure ids instead of redeclaring names and widths.",
        ),
        "ontology/decomposition.yaml": yaml_doc(
            "schema: oag_decomposition.v1",
            f"ip: {ip}",
            "profile:",
            "  mode: small_leaf_single_file",
            "  rationale: Seed scaffold uses one leaf RTL file until complexity or reuse requires module decomposition.",
            "  source: ontology/policies.yaml#structure_policy",
            "modules:",
            f"  - id: {ip}",
            f"    name: {ip}",
            "    role: top",
            "    ownership: current_ip",
            f"    file: rtl/{ip}.sv",
            "    implementation_style: small_leaf_single_file",
            f"    owned_obligations: [{obl_id}]",
            f"    owned_contracts: [{contract_id}]",
            "    structure_refs: []",
            "    source_refs: [ontology/requirements.yaml, ontology/obligations.yaml, ontology/contracts.yaml]",
            "    edit_policy: editable",
            "    notes: Replace this with greenfield_modular, legacy_preserve, or wrapper_adapter when the IP shape is known.",
            "interfaces: []",
            "legacy_sources: []",
        ),
        "ontology/design_rules.yaml": yaml_doc(
            "schema: oag_design_rules.v1",
            f"ip: {ip}",
            "rules:",
            "  - id: RULE_EVENT_STATE_COMMIT_CONSISTENCY",
            "    kind: event_state_commit_consistency",
            "    status: active",
            "    severity: signoff_block",
            "    text: Side-effect events and their state updates must use the same effective commit condition.",
            "    applies_when: interrupts, status bits, FSM transitions, counters, FIFOs, or handshakes produce side effects",
            "    requires: [event, state_update, commit_condition, contract]",
            "  - id: RULE_SAME_CYCLE_PRIORITY_DECLARED",
            "    kind: same_cycle_priority_declared",
            "    status: active",
            "    severity: signoff_block",
            "    text: Same-cycle conflicts must name the winning action in requirement truth.",
            "    applies_when: software writes, hardware updates, clears, sets, enables, disables, or terminal events can collide",
            "    requires: [conflict, priority, requirement, obligation, contract]",
            "  - id: RULE_SCOREBOARD_ROWS_V1",
            "    kind: scoreboard_evidence_schema",
            "    status: active",
            "    severity: block",
            "    text: Scoreboard evidence must use DUT-facing scoreboard_rows.v1 rows.",
            "    applies_when: expected-versus-observed evidence is submitted",
            "    requires: [goal_id, scenario_id, stimulus, expected, observed, observed_source, passed, mismatch, coverage_refs]",
            "  - id: RULE_CONTRACT_TO_PROOF_COVERAGE",
            "    kind: contract_to_proof_coverage",
            "    status: active",
            "    severity: signoff_block",
            "    text: A contract may only claim a proof scope that is backed by matching assertion, scoreboard, formal, coverage, or log evidence.",
            "    applies_when: any obligation is claimed closed",
            "    requires: [contract, proof_scope, evidence_ref]",
            "  - id: RULE_FAULT_MODEL_COVERAGE",
            "    kind: fault_model_coverage",
            "    status: active",
            "    severity: signoff_block",
            "    text: A load-bearing coverage point should name the requirement fault models it is meant to catch and, for signoff-grade claims, attach killed mutation evidence.",
            "    applies_when: coverage_refs are used as closure evidence for a requirement or obligation",
            "    requires: [requirement, obligation, contract, coverage_refs, fault_models, mutation_results]",
            "  - id: RULE_VERIFICATION_ROLE_DECOMPOSITION",
            "    kind: verification_role_decomposition",
            "    status: active",
            "    severity: signoff_block",
            "    text: Signoff-grade verification should separate UVM-style roles without requiring a specific TB framework.",
            "    applies_when: a testbench architecture is used as closure or signoff evidence",
            "    required_roles: [sequence, driver, monitor, reference_model, scoreboard, coverage, env, test]",
            "    requires: [requirement, obligation, contract, style, framework, roles, independence]",
            "  - id: RULE_CDC_CROSSING_COVERAGE",
            "    kind: cdc_crossing_coverage",
            "    status: active",
            "    severity: signoff_block",
            "    text: Clock/reset-domain crossing claims must name domains/crossings and attach CDC/RDC review or tool evidence.",
            "    applies_when: SSOT clock_reset_domains, cdc_requirements, or rdc_requirements are load-bearing closure facts",
            "    requires: [requirement, obligation, contract, clock_domains_or_crossings, evidence_refs]",
            "  - id: RULE_PROTOCOL_COMPLIANCE",
            "    kind: protocol_compliance",
            "    status: active",
            "    severity: signoff_block",
            "    text: Interface protocol claims such as AXI/APB/streaming handshakes must be backed by assertion, monitor, VIP, or protocol scoreboard evidence.",
            "    applies_when: an interface protocol is used as a design or integration closure claim",
            "    requires: [requirement, obligation, contract, protocol, evidence_refs]",
            "  - id: RULE_TIMING_CLOSURE",
            "    kind: timing_closure",
            "    status: active",
            "    severity: signoff_block",
            "    text: STA/timing closure claims must name target frequency or target clocks, derive SDC from those clocks plus CDC policy, and cite timing reports with setup/hold status.",
            "    applies_when: timing.target_clocks, timing.sta_expectations, SDC, syn, sta, or sta-post evidence is used for closure",
            "    requires: [requirement, obligation, contract, target_clocks_or_target_frequency, sdc_refs, timing_reports, evidence_refs]",
            "    default_io_delay_ratio: 0.5",
            "  - id: RULE_FUNCTIONAL_COVERAGE_CLOSURE",
            "    kind: functional_coverage_closure",
            "    status: active",
            "    severity: signoff_block",
            "    text: Functional coverage closure must tie coverage goals to observed coverage refs and coverage reports.",
            "    applies_when: coverage_functional, coverage_ssot, coverage.json, or scoreboard coverage refs are used as closure evidence",
            "    requires: [requirement, obligation, contract, coverage_refs, coverage_goal, coverage_actual, evidence_refs]",
            "  - id: RULE_RESET_XPROP_COVERAGE",
            "    kind: reset_xprop_coverage",
            "    status: active",
            "    severity: signoff_block",
            "    text: Reset and X-propagation closure must name reset scenarios or X-prop checks and attach observed evidence.",
            "    applies_when: reset behavior, async assert/sync deassert, reset-domain behavior, or X-prop robustness is load-bearing",
            "    requires: [requirement, obligation, contract, reset_scenarios_or_xprop_checks, coverage_refs, evidence_refs]",
            "  - id: RULE_MODULE_FILE_BOUNDARY",
            "    kind: module_file_boundary",
            "    status: active",
            "    severity: block",
            "    text: Greenfield modular IPs should map each current_ip module to a unique RTL file; shared files require explicit rationale.",
            "    applies_when: decomposition profile is greenfield_modular",
            "    requires: [module, file, ownership, shared_file_rationale_for_exception]",
            "  - id: RULE_RTL_LANGUAGE_SUBSET",
            "    kind: rtl_language_subset",
            "    status: active",
            "    severity: block",
            "    text: Generated RTL may use logic and Verilog generate for static elaboration; procedural loops remain forbidden outside generate blocks.",
            "    applies_when: RTL is authored, generated, repaired, linted, or promoted",
            "    allowed_constructs: [logic, generate, genvar, generate_for]",
            "    forbidden_constructs: [procedural_for, procedural_while, procedural_repeat, procedural_forever, package, import, interface, modport, typedef, enum, always_latch]",
            "    requires: [rtl_compile_report, language_policy]",
            "instances:",
            "  - id: TEMPLATE_EVENT_STATE_COMMIT",
            "    rule: RULE_EVENT_STATE_COMMIT_CONSISTENCY",
            "    status: template",
            "    note: Activate when this IP has side-effect events such as interrupts, status bits, FSM transitions, or terminal ticks.",
            "  - id: TEMPLATE_SAME_CYCLE_PRIORITY",
            "    rule: RULE_SAME_CYCLE_PRIORITY_DECLARED",
            "    status: template",
            "    note: Activate for pairs such as clear-vs-set, write-vs-hardware-update, enable-vs-terminal-tick, or reset-vs-valid.",
            "  - id: TEMPLATE_CONTRACT_PROOF_COVERAGE",
            "    rule: RULE_CONTRACT_TO_PROOF_COVERAGE",
            "    status: template",
            "    note: Activate when a contract is promoted beyond draft or claims formal/assertion coverage.",
            "  - id: TEMPLATE_FAULT_MODEL_COVERAGE",
            "    rule: RULE_FAULT_MODEL_COVERAGE",
            "    status: template",
            "    note: Activate when a coverage point is used as load-bearing closure evidence and should be tied to killed requirement-relevant mutants.",
            "  - id: TEMPLATE_VERIFICATION_ROLE_DECOMPOSITION",
            "    rule: RULE_VERIFICATION_ROLE_DECOMPOSITION",
            "    status: template",
            "    note: Activate for signoff-grade TB architecture; use UVM concepts such as sequence, driver, monitor, reference model, scoreboard, coverage, env, and test without requiring UVM itself.",
            "  - id: TEMPLATE_CDC_CROSSING_COVERAGE",
            "    rule: RULE_CDC_CROSSING_COVERAGE",
            "    status: template",
            "    note: Activate when SSOT clock_reset_domains/cdc_requirements/rdc_requirements make crossing safety a closure claim.",
            "  - id: TEMPLATE_PROTOCOL_COMPLIANCE",
            "    rule: RULE_PROTOCOL_COMPLIANCE",
            "    status: template",
            "    note: Activate for AXI, APB, streaming, valid/ready, or other interface protocol compliance closure.",
            "  - id: TEMPLATE_TIMING_CLOSURE",
            "    rule: RULE_TIMING_CLOSURE",
            "    status: template",
            "    note: Activate when SDC, STA, syn, or sta-post reports are part of closure or signoff evidence. Use target_clocks or target_frequency_mhz to derive create_clock; derive async clock groups or CDC exceptions from CDC/RDC facts; default input/output delay ratio is 0.5 of clock period unless the IP overrides it.",
            "  - id: TEMPLATE_FUNCTIONAL_COVERAGE_CLOSURE",
            "    rule: RULE_FUNCTIONAL_COVERAGE_CLOSURE",
            "    status: template",
            "    note: Activate when coverage_functional, coverage_ssot, or coverage refs are used to close requirements.",
            "  - id: TEMPLATE_RESET_XPROP_COVERAGE",
            "    rule: RULE_RESET_XPROP_COVERAGE",
            "    status: template",
            "    note: Activate for reset sequencing, async assert/sync deassert, reset-domain, or X-prop robustness closure.",
        ),
        "ontology/stages.yaml": yaml_doc(
            "schema: oag_stage_contracts.v1",
            f"ip: {ip}",
            "stages:",
            "  - id: req",
            "    owner: human-owner",
            "    inputs: [req/locked_truth.md, req/requirements.yaml]",
            "    outputs: [ontology/requirements.yaml, ontology/obligations.yaml, ontology/contracts.yaml]",
            "    gate: oag.compile",
            "  - id: rtl",
            "    owner: rtl",
            "    inputs: [ontology/generated/design_truth_graph.json, list/rtl.f]",
            "    outputs: [rtl/rtl_compile.json]",
            "    gate: rtl_compile",
            "  - id: tb",
            "    owner: tb",
            "    inputs: [ontology/generated/design_truth_graph.json, rtl/rtl_compile.json]",
            "    outputs: [sim/scoreboard_events.jsonl]",
            "    gate: scoreboard_rows.v1",
            "  - id: sim",
            "    owner: sim",
            "    inputs: [rtl/rtl_compile.json, sim/scoreboard_events.jsonl]",
            "    outputs: [sim/results.xml]",
            "    gate: sim_results",
            "  - id: signoff",
            "    owner: signoff",
            "    inputs: [ontology/generated/design_truth_graph.json, ontology/evidence/stage_runs]",
            "    outputs: [signoff/release.yaml]",
            "    gate: oag.decide.signoff",
        ),
        "ontology/policies.yaml": yaml_doc(
            "schema: oag_policy.v1",
            f"ip: {ip}",
            "closure_profile: development",
            "execution_policy:",
            "  hook_auto_continue_until: all",
            "  stop_hook_max_repeats: 3",
            "graph_policy:",
            "  context_uses_cached_graph: true",
            "  compile_skip_when_fresh: true",
            "  strict_fresh_on: [checkpoint, check, signoff]",
            "structure_policy:",
            "  default_profile: small_leaf_single_file",
            "  allowed_profiles: [greenfield_modular, small_leaf_single_file, legacy_preserve, wrapper_adapter]",
            "  single_file_allowed_when: small leaf IP with explicit rationale and module ownership",
            "  greenfield_modular_requires: [decomposition, module_ownership, unique_module_files, interface_contracts]",
            "  legacy_preserve_requires: [legacy_sources, preserve_existing_hierarchy]",
            "  wrapper_adapter_requires: [legacy_core, wrapper_module, boundary_contracts]",
            "profiles:",
            "  draft:",
            "    intent: authoring and exploration",
            "    may_claim_signoff: false",
            "  development:",
            "    intent: normal IP development with real evidence",
            "    may_claim_signoff: false",
            "  signoff:",
            "    intent: audit-grade closure",
            "    may_claim_signoff: true",
            "action_policy:",
            "  claim_complete:",
            "    requires: [rocev_chain, explicit_validation_status, closure_matrix, evidence_hash_freshness, append_only_ledger, monotonic_closure, decision_receipt]",
            "  close_obligation:",
            "    requires: [rocev_chain, explicit_validation_status, closure_matrix, evidence_hash_freshness, append_only_ledger, monotonic_closure]",
            "  promote:",
            "    requires: [closed_validation, closure_matrix, decision_receipt, protected_fields_clean, human_review, enterprise_promotion_record]",
            "  signoff:",
            "    requires: [closed_obligations, closure_matrix, decision_receipt, truth_graph_compiled, fresh_stage_receipts, protected_fields_clean, append_only_ledger, monotonic_closure, human_approval]",
        ),
        "ontology/protection.yaml": yaml_doc(
            "schema: oag_protection_policy.v1",
            f"ip: {ip}",
            "policy:",
            "  semantic_change_requires: human_approval_or_decision_record",
            "  default_actor: untrusted_ai_client",
            "protected_paths:",
            "  - req/locked_truth.md",
            "  - req/requirements.yaml",
            "  - req/evidence_plan.yaml",
            "  - ontology/requirements.yaml",
            "  - ontology/obligations.yaml",
            "  - ontology/contracts.yaml",
            "  - ontology/structure.yaml",
            "  - ontology/decomposition.yaml",
            "  - ontology/policies.yaml",
            "protected_fields:",
            "  - requirements[].text",
            "  - obligations[].text",
            "  - obligations[].requirement",
            "  - contracts[].obligation",
            "  - contracts[].method",
            "  - contracts[].pass_condition",
            "  - structure_policy",
            "  - profile.mode",
            "  - modules[].ownership",
            "  - modules[].owned_obligations",
            "  - modules[].owned_contracts",
            "  - closure_profile",
            "  - execution_policy",
            "  - graph_policy",
            "  - profiles.signoff",
            "approval_record:",
            "  tool: oag.record",
            "  required_actor_kind: human",
            "  required_type: decision",
        ),
        "ontology/evidence/scoreboard_rows.v1.yaml": yaml_doc(
            "schema: evidence_schema.v1",
            "id: scoreboard_rows.v1",
            "artifact: sim/scoreboard_events.jsonl",
            "format: jsonl",
            "policy:",
            "  tb_implementation: free",
            "  accepted_tb_styles:",
            "    - verilog",
            "    - systemverilog",
            "    - uvm",
            "    - cocotb",
            "    - python",
            "    - simulator_adapter",
            "  fixed_contract: row semantics and required fields",
            "required_fields:",
            "  - goal_id",
            "  - scenario_id",
            "  - cycle",
            "  - stimulus",
            "  - expected",
            "  - observed",
            "  - observed_source",
            "  - passed",
            "  - mismatch",
            "  - coverage_refs",
            "expected_source_kinds:",
            "  - fl_model",
            "  - cl_model",
            "  - golden_vector",
            "  - assertion",
            "  - manual_spec",
            "  - reference_log",
            "observed_source_kinds:",
            "  - dut_signal",
            "  - monitor",
            "  - waveform",
            "  - transaction",
            "  - assertion",
            "  - interface_sample",
            "  - bus_monitor",
            "rules:",
            "  - observed_source.kind must describe DUT observation, not a model source",
            "  - observed must be sampled from DUT-facing signals, monitors, waves, transactions, or assertions",
            "  - expected may come from a model, vector, assertion, spec, or reference log",
            "  - a passing row must not carry a mismatch explanation",
            "  - a failing row must carry a mismatch explanation",
        ),
        "ontology/evidence/stage_run_receipt.v1.yaml": yaml_doc(
            "schema: evidence_schema.v1",
            "id: stage_run_receipt.v1",
            "artifact: ontology/evidence/stage_runs/<stage>.json",
            "format: json",
            "required_fields:",
            "  - stage",
            "  - owner",
            "  - status",
            "  - command",
            "  - actor",
            "  - started_at",
            "  - completed_at",
            "  - input_fingerprints",
            "  - output_fingerprints",
            "freshness_rule: every fingerprint path must exist on disk and sha256 must match current file content",
        ),
        "ontology/evidence/formal_assertion_report.v1.yaml": yaml_doc(
            "schema: evidence_schema.v1",
            "id: formal_assertion_report.v1",
            "artifact: signoff/formal_assertion_report.json",
            "format: json",
            "required_fields:",
            "  - schema_version",
            "  - ip",
            "  - status",
            "  - closure_profile",
            "  - method",
            "  - checks",
            "  - properties",
            "  - issues",
            "  - signoff_limitations",
            "  - evidence_refs",
            "rule: status=development_pass is development evidence only; auto research must rank it as partially_closed unless a promoted formal contract and signoff evidence exist",
        ),
        "ontology/metrics/improvement_metrics.v1.yaml": yaml_doc(
            "schema: metrics_schema.v1",
            "id: oag_improvement_metrics.v1",
            "artifact: ontology/metrics/improvement_metrics.json",
            "history: ontology/metrics/improvement_history.jsonl",
            "format: json",
            "scope: generic IP progress measurement; obligation counts are derived from each IP ontology and are not fixed",
            "required_numeric_groups:",
            "  - closure",
            "  - check",
            "  - evidence",
            "  - stage_receipts",
            "  - ledger",
            "  - design",
            "  - auto_research",
            "  - decisions",
            "rule: use oag.metrics after meaningful improvement boundaries so progress can be compared numerically across IPs",
        ),
        "ontology/handoff_readiness.v1.yaml": yaml_doc(
            "schema: action_schema.v1",
            "id: oag_readiness_handoff.v1",
            "artifact: handoff/readiness_handoff.json",
            "history: handoff/readiness_history.jsonl",
            "format: json",
            "scope: generic IP readiness handoff derived from OAG metrics and auto-research reports",
            "required_fields:",
            "  - schema_version",
            "  - numeric_summary",
            "  - readiness",
            "  - ranked_next_actions",
            "  - signoff_blockers",
            "  - evidence_refs",
            "rule: development_ready and signoff_ready must be numerically derived; development closure must not be presented as signoff readiness",
        ),
        "ontology/decision_receipt.v1.yaml": yaml_doc(
            "schema: action_schema.v1",
            "id: oag_decision_receipt.v1",
            "artifact: ontology/validations/<decision_id>.json",
            "format: json",
            "required_fields:",
            "  - id",
            "  - action",
            "  - allowed",
            "  - reason",
            "  - actor",
            "  - evidence",
            "  - ledger_event",
            "rule: completion decisions must be recorded after oag.check/oag.inspect and hash-chained into knowledge/ledger.jsonl",
        ),
        "ontology/run_state.v1.yaml": yaml_doc(
            "schema: action_schema.v1",
            "id: oag_run_state.v1",
            "artifact: ontology/runs/<run_id>/run_state.json",
            "format: json",
            "required_fields:",
            "  - run_id",
            "  - status",
            "  - active_obligation",
            "  - active_contracts",
            "  - next_action",
            "  - last_checkpoint",
            "rule: run state drives one next action but closure remains governed by ROCEV records and decision receipts",
        ),
        "ontology/failure_ticket.v1.yaml": yaml_doc(
            "schema: action_schema.v1",
            "id: failure_ticket.v1",
            "artifact: handoff/failure_tickets/<ticket_id>.json",
            "required_fields:",
            "  - failing_contract",
            "  - owner_workflow",
            "  - expected",
            "  - observed",
            "  - evidence",
            "  - editable_files",
            "  - forbidden_edits",
            "  - required_evidence_after_patch",
            "rule: agents repair one unclosed contract at a time and never edit locked truth",
        ),
        "ontology/gates/gate_self_test_registry.yaml": yaml_doc(
            "schema: oag_gate_self_test_registry.v1",
            f"ip: {ip}",
            "gates:",
            "  - id: scoreboard_rows.v1",
            "    validator: oag.inspect.scoreboard",
            "    status: covered",
            "    positive_fixture: sim/scoreboard_events.jsonl",
            "    mutation_tests: [missing_observed_source, model_observed_source, empty_observed]",
            "  - id: design_truth_graph",
            "    validator: oag.compile",
            "    status: covered",
            "    positive_fixture: ontology/requirements.yaml",
            "    mutation_tests: [missing_requirement_id, orphan_obligation, orphan_contract]",
            "  - id: stage_run_receipt.v1",
            "    validator: oag.check.stage_receipts",
            "    status: open",
            "    mutation_tests: [missing_output, fingerprint_mismatch]",
            "  - id: formal_assertion_auto_research",
            "    validator: oag.check.auto_research",
            "    status: covered",
            "    mutation_tests: [development_formal_marked_closed, missing_bounded_limitation, missing_contract_signoff_limitation]",
            "  - id: improvement_metrics",
            "    validator: oag.metrics",
            "    status: covered",
            "    mutation_tests: [metrics_snapshot_missing_history, closure_percent_regression_visibility]",
            "  - id: readiness_handoff",
            "    validator: oag.check.handoff",
            "    status: covered",
            "    mutation_tests: [development_marked_signoff_ready, numeric_summary_mismatch, missing_handoff_evidence_ref]",
            "  - id: protected_fields",
            "    validator: oag.check.protection",
            "    status: covered",
            "    mutation_tests: [unapproved_locked_truth_edit, missing_protection_policy]",
            "  - id: append_only_ledger",
            "    validator: oag.check.ledger",
            "    status: covered",
            "    mutation_tests: [payload_tamper, prev_hash_mismatch, invalid_jsonl]",
            "  - id: monotonic_closure",
            "    validator: oag.check.monotonic",
            "    status: covered",
            "    mutation_tests: [closed_to_open_without_decision]",
            "  - id: module_file_boundary",
            "    validator: oag.compile.decomposition",
            "    status: covered",
            "    mutation_tests: [greenfield_modules_share_file_without_rationale]",
            "  - id: verified_completion",
            "    validator: oag.check.closure_matrix",
            "    status: covered",
            "    mutation_tests: [missing_validation_status, stale_evidence_hash, missing_decision_receipt]",
        ),
        "ontology/actors.yaml": yaml_doc(
            "schema: ontology_actors.v1",
            f"ip: {ip}",
            "actors:",
            "  - id: human-owner",
            "    kind: human",
            f"    owner: {owner}",
            "  - id: codex",
            "    kind: ai",
            "    surface: cli",
        ),
        "ontology/actions.yaml": yaml_doc(
            "schema: ontology_actions.v1",
            f"ip: {ip}",
            "actions: []",
        ),
        "list/rtl.f": yaml_doc("+incdir+rtl", "rtl/*.sv"),
        "list/tb.f": yaml_doc("+incdir+tb", "tb/*.sv", "tb/cocotb/*.py"),
        "list/sim.f": yaml_doc("-f list/rtl.f", "-f list/tb.f"),
        "list/lint.f": yaml_doc("-f list/rtl.f"),
        "list/syn.f": yaml_doc("-f list/rtl.f"),
        "doc/design.md": yaml_doc(
            f"# {ip} Design",
            "",
            "## Intent",
            "",
            "## Interfaces",
            "",
            "## State",
            "",
            "## Reset Behavior",
        ),
        "doc/verification.md": yaml_doc(
            f"# {ip} Verification",
            "",
            "## Contracts",
            f"- `{contract_id}`",
            "",
            "## Scoreboard Evidence",
            "- TB implementation is free: Verilog, SystemVerilog, UVM, Python, cocotb, or simulator adapter.",
            "- The submitted evidence row schema is fixed: `ontology/evidence/scoreboard_rows.v1.yaml`.",
            "",
            "## Evidence",
            "- sim/results.xml",
            "- sim/scoreboard_events.jsonl",
        ),
        "doc/signoff.md": yaml_doc(
            f"# {ip} Signoff",
            "",
            "Do not sign off until OAG decide allows `claim_complete`.",
            "",
            "Signoff must keep protected fields clean, ledger hash-chain valid, and closed objects monotonic.",
        ),
        "scripts/run_sim.sh": yaml_doc(
            "#!/usr/bin/env bash",
            "set -euo pipefail",
            "mkdir -p sim",
            "echo 'TODO: connect simulator command for this IP'",
        ),
        "scripts/run_lint.sh": yaml_doc(
            "#!/usr/bin/env bash",
            "set -euo pipefail",
            "mkdir -p lint/reports",
            "echo 'TODO: connect lint command for this IP'",
        ),
        "signoff/release.yaml": yaml_doc(
            "schema: ip_release.v1",
            f"ip: {ip}",
            "status: draft",
            "validations: []",
        ),
    }


def build_seed_graph(ip: str) -> dict[str, Any]:
    req_id = f"REQ_{ip.upper()}_001"
    obl_id = f"OBL_{ip.upper()}_RESET_KNOWN"
    contract_id = f"CONTRACT_{ip.upper()}_SIM_SCOREBOARD"
    return {
        "schema_version": "oag_ontology_graph.v1",
        "generated_at": now(),
        "ip": ip,
        "nodes": [
            {"id": f"ip::{ip}", "type": "ip", "label": ip, "status": "draft"},
            {"id": f"requirement::{req_id}", "type": "requirement", "label": req_id, "status": "draft"},
            {"id": f"obligation::{obl_id}", "type": "obligation", "label": obl_id, "status": "open"},
            {"id": f"contract::{contract_id}", "type": "contract", "label": contract_id, "status": "draft"},
        ],
        "edges": [
            {"source": f"ip::{ip}", "target": f"requirement::{req_id}", "label": "has_requirement"},
            {"source": f"requirement::{req_id}", "target": f"obligation::{obl_id}", "label": "has_obligation"},
            {"source": f"obligation::{obl_id}", "target": f"contract::{contract_id}", "label": "judged_by"},
        ],
    }


def cmd_create(args: argparse.Namespace) -> int:
    manifest = scaffold(Path(args.ip_dir), force=args.force, owner=args.owner)
    print(json.dumps(manifest, ensure_ascii=False, indent=2))
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)
    create = sub.add_parser("create", help="create an ontology-first IP scaffold")
    create.add_argument("ip_dir")
    create.add_argument("--owner", default="unassigned")
    create.add_argument("--force", action="store_true")
    create.set_defaults(func=cmd_create)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
